#define	CONF_VERSION	"1.05.04_V_G"
#define	CONF_PRODUCT_EXT_WDTV_VILLA
#define	CONF_PRODUCT_SN	"WDTV_SN"
#define	CONF_UI_LOGIC_VILLA
#define	CONF_BASIC_PAGES_WD
#define	CONF_UI_LOGIC	"VILLA_pages"
#define	CONF_RESOURCE_VILLA
#define	CONF_RESOURCE	"RES_VILLA"
#define	CONF_MODEL_WW
#define	CONF_MODEL	"ww"
#define	CONF_TVDOCK
#define	CONF_PRODUCT	"TVDOCK"
#define	CONF_CONFIG_HEADER_TYPE	"A"
#define	CONF_CONFIG_HEADER_VERSION	"1"
#define	CONF_BUILD_GPL_FIRMWARE
#define	CONF_PLATFORM_SMP8654
#define	CONF_PLATFORM_SMP8654_WISTRON_VILLA_BOARD_D2
#define	CONF_COMPILE_WITH_GFLAG	""
#define	CONF_COMPILE_WITH_OPTIMIZE	"-O"
#define	CONF_PLATFORM_SMP8654_SDK_3_8_8
#define	CONF_PLATFORM_SMP8654_SDK_SUBVERSION_rc_6
#define	CONF_SUPPORT_DCCHD
#define	CONF_SUPPORT_DCCHD_DVD_BD_NAVIGATION
#define	CONF_3_8_8_rc_6_AQUA
#define	CONF_DCCHD_VERSION	"SMP8654_3_8_8_rc_6_aqua.mips"
#define	CONF_DIRECTFBRC_BUILDER
#define	CONF_USE_DIRECTFB_PORTING_SOURCECODE
#define	CONF_DIRECTFB_PORTING_VERSION	"SMP8654_3_8_8_rc_6_porting.mips"
#define	CONF_MMAP_DOUBLE_TO_SINGLE
#define	CONF_DIRECTFB_OVERWRITE_SIMGA_PNG_PATCH
#define	CONF_DCCHD_FIX_AVCHD_PLAY_FAIL_BUT_NO_RETURN
#define	CONF_DCCHD_FIX_DVD_PALY_FAIL_AND_SYSTEM_BLOCK
#define	CONF_DCCHD_FIX_DVD_PCR_FAIL
#define	CONF_DIRECTFB_HDMI_FIX_1080P24_SWITCHING
#define	CONF_DIRECTFB_FIX_COLOR_SPACE
#define	CONF_DIRECTFB_FIX_CRASH_IN_INVALID_ISO
#define	CONF_DCCHD_FIX_HDMI_SPD_TO_WDTV
#define	CONF_PLATFORM_SMP8654_SDK_3_7_0_ORIGINAL_KERNEL_PATCH
#define	CONF_SUPPORT_DRIVE_LARGER_THAN_2T
#define	CONF_PLATFORM_SMP8654_TOOLCHAIN_GNU_4_3_2
#define	CONF_SIGMA_EZBOOT_0X98_NAND_FLASH_DRIVER
#define	CONF_SIGMA_YAMON_R2_13_24_NAND_FLASH_DRIVER
#define	CONF_LINUX_KERNEL_2_6_22_19_27_NAND_FLASH_DRIVER
#define	CONF_DTS_CHIP_SET
#define	CONF_NAND_FLASH_PATCH_05122010
#define	CONF_TOOLCHAIN_FILENAME	"mips-4.3.tgz"
#define	CONF_CROSS_BIN	"/opt/mips-4.3/bin/"
#define	CONF_CROSS	"$(CROSS_BIN)/mipsel-linux-"
#define	CONF_CROSS_PREFIX	"/opt/mips-4.3/"
#define	CONF_SIGMA_SDK_VERSION	"3_8_0"
#define	CONF_BUILD_DMAOSD
#define	CONF_BUILD_DMARENDER
#define	CONF_BUILD_MISC
#define	CONF_BUILD_MEDIALOGIC
#define	CONF_BUILD_EXTERNAL_PACKAGES
#define	CONF_BUILD_ROOTFS
#define	CONF_BUILD_ROOTFS_PRIMARY_SYSTEM
#define	CONF_BUILD_FIRMWARE
#define CONF_REPOSITORY_IP
#define	CONF_REPOSITORY_PATH	"dmax/trunk"
#define	CONF_SPECIFY_SVN_VERSION
#define	CONF_SVN_VERSION	81207
#define	CONF_ENABLE_NETWORKING
#define	CONF_DMA_SLAVEMODE
#define	CONF_ENABLE_REGISTRATION
#define	CONF_SUPPORT_CHECK_CONNECTION
#define	CONF_CHECK_CONNECTION_HOST	"www.wdc.com"
#define	CONF_LAN_INTERFACE	"eth0"
#define	CONF_ENABLE_AUTOIP
#define	CONF_WIRELESS_SUPPORT
#define	CONF_DROP_DUPLICATE_SSID
#define	CONF_WIRELESS_PROFILE_SUPPORT
#define	CONF_WIRELESS_PROFILE_NUM	5
#define	CONF_WIRELESS_PROFILE_PAGE_SUPPORT
#define	CONF_WIRELESS_PREFERENCE_IN_SETUP_WIZARD
#define	CONF_WIRELESS_TOOLS
#define	CONF_WLAN_INTERFACE	"eth1"
#define	CONF_WIRELESS_SITE_SURVEY_SORT_BY_SIGNAL_STRENGTH
#define	CONF_WIRELESS_RALINK_SOLUTION
#define	CONF_WIRELESS_USB_DONGLE
#define	CONF_WIRELESS_RTL8712
#define	CONF_WIRELESS_AR9170
#define	CONF_WIRELESS_RT2870
#define	CONF_RT2870_VERSION_2_1_0_0
#define	CONF_WIRELESS_RT3070
#define	CONF_RT3070_VERSION_2_1_0_0
#define	CONF_WIRELESS_RT3572
#define	CONF_RT3572_VERSION_2_1_2_0
#define	CONF_WPA_SUPPLICANT
#define	CONF_SAMBA
#define	CONF_SAMBA_VERSION_3_5_1
#define	CONF_SAMBA_VERSION	"3.5.1"
#define	CONF_SAMBA_WORKGROUP
#define	CONF_SAMBA_INSTALL_SMBCLIENT
#define	CONF_SAMBA_CONF_PATH	"/tmp/smb.conf"
#define	CONF_SAMBA_MOUNT_POINT	"/tmp/"
#define	CONF_AUTO_LOGIN
#define	CONF_SAMBA_CLIENT_SUPPORT_SERVERLIST_REFRESH
#define	CONF_CLEAR_USERACCOUNT
#define	CONF_CLEAR_ALL_USERINFO
#define	CONF_SAMBA_CIFS_MOUNT_READ_WRITE
#define	CONF_DMA_UPNP
#define	CONF_DEVICE_MODEL_DESC	"WD TV HD Live Media Player"
#define	CONF_DEVICE_MODEL_NAME	"WD TV HD Live"
#define	CONF_DEVICE_MODEL_NUM	"WDA4NC40000"
#define	CONF_DEVICE_MODEL_URL	"http://www.wdtvlive.com/"
#define	CONF_DEVICE_MANUFACTURER_URL	"http://www.wdc.com"
#define	CONF_DEVICE_MANUFACTURER_NAME	"Western Digital Corporation"
#define	CONF_DMA_DLNA
#define	CONF_WMC_WITH_WRONG_BITRATE
#define	CONF_WIN7_WAKEONLAN
#define	CONF_DEVICE_NAME	"WDTVLIVE"
#define	CONF_HOME_ENTER_ALWAYS_SERVER_LIST
#define	CONF_MOVE_DEFAULT_M_SERVER_FIRST
#define	CONF_SAMBA_SERVER
#define	CONF_SAMBA_SERVER_SUPPORT_SECURITY
#define	CONF_SAMBA_FTRUNCATE_PATCH
#define	CONF_SAMBA_SERVER_SCRIPT	"/bin/run_samba"
#define	CONF_SAMBA_SERVER_DESCRIPTIVE_COMMENT_STRING	"WDTV LIVE"
#define	CONF_SAMBA_SERVER_RENAME_DUPLICATE_NAME_METHOD1
#define	CONF_DMA_VILLA_ONLINE_MATRIX
#define	CONF_DMA_FLICKR
#define	CONF_DMA_FLICKR_WITH_SEARCH_HEAD
#define	CONF_FLICKR_API_KEY_WD
#define	CONF_DMA_FLICKR_API_KEY	""
#define	CONF_DMA_FLICKR_SCRECT_KEY	""
#define	CONF_HOWL
#define	CONF_ITUNE_SUPPORT
#define	CONF_OSD_ENGINE_DFB_DOUBLE_BUFFER
#define	CONF_OSD_ENGINE_STATIC_IMAGE_BUF_SIZE	524288
#define	CONF_OSD_ENGINE_HTTP_IMAGE
#define	CONF_ENGINE_HAL
#define	CONF_BG_ON_OSD
#define	CONF_OSD_IMG_CACHE_LARGE	3
#define	CONF_OSD_IMG_CACHE_MEDIUM	24
#define	CONF_OSD_IMG_CACHE_SMALL	16
#define	CONF_OSD_IMG_CACHE_LARGE_THRES	345600
#define	CONF_OSD_IMG_CACHE_MEDIUM_THRES	6400
#define	CONF_MAX_THUMB_CATCH_SIZE	3145728
#define	CONF_MAX_THUMB_CATCH_NUMBER	10000
#define	CONF_DRAW_OSD_TEXT_BY_ALE
#define	CONF_ALE_TEXT_CACHE_SIZE	1048576
#define	CONF_PREFETCH_LIST_NUM	60
#define	CONF_THUMBNAIL_CACHE_ON_STORAGE
#define	CONF_THUMBNAIL_CACHE_ON_STORAGE_FOLDER	"thumb"
#define	CONF_CAS_BROWSE_DATE_DESCEND
#define	CONF_CAS_SEARCH_FILENAME_IN_AUDIO_AND_PLAYLIST
#define	CONF_DMA_HD_UI
#define	CONF_DMA_DEPTH32
#define	CONF_ONLINE_IMAGE_LOCAL_PATH	"/tmp/local_file"
#define	CONF_LAVENDER_UI
#define	CONF_OSD_FADING_UI_EFFECT
#define	CONF_OSD_HOME_CROSSBAR_V2
#define	CONF_OSD_HOME_CROSSBAR_V2_MODE1
#define	CONF_QUICK_SHOW_BG	"image/welcome_background_bg.jpg"
#define	CONF_OSD_WIDTH	1280
#define	CONF_OSD_HEIGHT	720
#define	CONF_JPEG_THUMBNAIL_MAX_W	240
#define	CONF_JPEG_THUMBNAIL_MAX_H	240
#define	CONF_MAX_SUPPORTED_PROGRESSIVE_JPEG_SIZE	16777216
#define	CONF_MAX_SUPPORTED_THUMBNAIL_PROGRESSIVE_JPEG_SIZE	921600
#define	CONF_MAX_SUPPORTED_THUMBNAIL_PNG_SIZE	345600
#define	CONF_MAX_SUPPORTED_THUMBNAIL_GIF_SIZE	345600
#define	CONF_GFX
#define	CONF_GFX_WAIT_FOR_COMMAND
#define	CONF_DISABLE_VIDEO_OUTPUT_IN_POWER_OFF
#define	CONF_ENABLE_HOME_PLAYING_INFO
#define	CONF_QUICK_MENU
#define	CONF_OSD_ENABLE_SCREENSAVER
#define	CONF_THUMB_VARIOUS_EXTRACT_SUPPORT
#define	CONF_SHOW_FILESIZE
#define	CONF_SLIDESHOW_INTERVAL	3
#define	CONF_PREV_NEXT_AS_PGUP_PGDN
#define	CONF_SPLASH_SCREEN_NTSC_PAL_SWITCH
#define	CONF_EZBOOT_SUPPORT_FAIL_SAFE_SPLASH_SCREEN
#define	CONF_USING_CREDIT
#define	CONF_OSD_SUPPORT_PREVIEW_PAGE
#define	CONF_PREVIEW_MODE_SUPPORT_FF_REV
#define	CONF_PREVIEW_MODE_SUPPORT_VIDEO_FOLDER_ICON_AND_THUMBNAIL
#define	CONF_PREVIEW_WINDOW_VILLA
#define	CONF_OSD_PREVIEW_WIN_X	778
#define	CONF_OSD_PREVIEW_WIN_Y	179
#define	CONF_OSD_PREVIEW_WIN_W	333
#define	CONF_OSD_PREVIEW_WIN_H	222
#define	CONF_SHOW_AUDIO_NAME_ON_PAGEUI
#define	CONF_SHOW_AUDIO_CODEC_ON_PAGEUI
#define	CONF_CASE1_AUDIO_SHOW_INFO_STYLE
#define	CONF_AUDIO_SHOW_INFO_STYLE_IN_VIDEO_PAGE	1
#define	CONF_CASE1_SUBTITLE_SHOW_INFO_STYLE
#define	CONF_SUBTITLE_SHOW_INFO_STYLE_IN_VIDEO_PAGE	1
#define	CONF_ENABLE_GUI_HANDLER
#define	CONF_GUI_HANDLER_THREAD
#define	CONF_DIGITAL_WITHOUT_HDMI_AUDIO
#define	CONF_KEYBOARD_SUPPORT_EU
#define	CONF_SINGLE_RENDERER
#define	CONF_INDEPENDENT_BROWSE_DISPLAY
#define	CONF_PHOTO_BROWSE_DISPLAY_DEFAULT_IS_THUMBNAIL
#define	CONF_VIDEO_BROWSE_DISPLAY_DEFAULT_IS_VIDEO
#define	CONF_MUSIC_BROWSE_DISPLAY_DEFAULT_IS_THUMBNAIL
#define	CONF_HOME_CROSSBAR_DEFAULT_IS_VIDEO
#define	CONF_DISABLE_CONTROL_OSD_FROM_STD_INPUT
#define	CONF_DMA_HDMI
#define	CONF_MULTI_LANGUAGE
#define	CONF_HEBREW_AND_ARABIC_SUPPORT
#define	CONF_DMA_SUBTITLE
#define	CONF_ZOOM_IN_OUT_CASE3
#define	CONF_PLAYER_CHAPTER_SUPPORT
#define	CONF_MKV_CHAPTER_SUPPORT
#define	CONF_MOV_CHAPTER_SUPPORT
#define	CONF_HDMI_ALWAYS_OUTPUT_RGB
#define	CONF_HDMI_3_7_1_fix_FPE
#define	CONF_VIDEO_QUICK_JUMP
#define	CONF_PICTURE_AUTO_ORIENTATION
#define	CONF_ADDITIONAL_ENCODING_SUPPORT
#define	CONF_HD_PHOTO_PLAYER
#define	CONF_GIF_PLAY_SINGLE_FRAME
#define	CONF_TIFF_PLAY_SINGLE_FRAME
#define	CONF_NTSC_PAL_SWITCHING
#define	CONF_NTSC_OR_PAL_UNUPGRADABLE
#define	CONF_LOCAL_BROWSE
#define	CONF_LOCAL_PLAYLIST
#define	CONF_LOCAL_PLAYLIST_PARSE_BUFFER_SIZE	102400
#define	CONF_SLIDE_SHOW_SECOND_INDEX_0_IS	3
#define	CONF_SLIDE_SHOW_1_MIN_INDEX	28
#define	CONF_SLIDE_SHOW_2_MINS_INDEX	"29"
#define	CONF_THUMB_WMA
#define	CONF_THUMB_MP4
#define	CONF_DMA_AUDIO_ALBUM_ART
#define	CONF_DMA_LOCAL_BROWSE_THUMB
#define	CONF_LOCAL_THUMBNAIL_MAX_SIZE	102400
#define	CONF_DMA_AUDIO_TRACK_SWITCH
#define	CONF_DMA_FONT_FREETYPE2
#define	CONF_ENABLE_LOGO4WMC
#define	CONF_SAFE_MODE
#define	CONF_BROWSE_HANDLER
#define	CONF_BROWSE_CACHE
#define	CONF_USE_SERVER_HANDLER
#define	CONF_PHOTO_SLIDESHOW_NO_RESUME_PLAYING_WITH_PREV_NEXT
#define	CONF_PLAYLIST_SHUFFLE_LIMITED
#define	CONF_FILEOP
#define	CONF_BROWSE_DO_FILEOP
#define	CONF_RUA_MEMORY_ALLOC_BANK1_FIRST
#define	CONF_POWER_ON_OFF_WITH_ETHERNET_UP_DOWN
#define	CONF_SAVE_DEFAULT_SETTING_IN_LAST_PARTITON
#define	CONF_LAST_PARTITION_NODE_NAME	"/dev/sigmblockl"
#define	CONF_STATIC_CONFIG_MOUNT_POINT	"/tmp/static_config"
#define	CONF_SUPPORT_SYSTEM_ACCOUNT
#define	CONF_DEBOUNCE_NTSC_PAL_KEY_TIME	10
#define	CONF_RTC_TOOL
#define	CONF_NTSC_OR_PAL	"NTSC"
#define	CONF_NTSC_M
#define	CONF_COMPONENT_SUPPORT_RGB_COLOR_SPACE
#define	CONF_SUPPORT_COMPONENT_OUTPUT_IN_TVDOCK
#define	CONF_HDMI_REPLACE_PREFERRED_MODE_TO_1080P
#define	CONF_GET_HDMI_VIC
#define	CONF_HDMI_AUTO_NATIVE_MODE
#define	CONF_HDMI_SAVE_TV_MODEL
#define	CONF_HDMI_COMPATIBLE_MODE
#define	CONF_HDMI_FORCE_OUTPUT_UNSUPPORTED_RESOLUTION
#define	CONF_HDMI_LOCK_FUNCTION
#define	CONF_APPLY_DISPLAY_IF_ASPECT_RATIO_CHANGED
#define	CONF_IRDA_DFB_EVENT
#define	CONF_WD_APOLLO_DRIVE_UNLOCK_SUPPORT
#define	CONF_STORAGE_SUPPORT
#define	CONF_REMOVABLE_DEVICE_MANAGER
#define	CONF_FUSE_MOUNT_SUPPORT
#define	CONF_NTFS_SUPPORT
#define	CONF_NTFS_3G_SUPPORT
#define	CONF_FAT_SUPPORT
#define	CONF_DOSFSTOOLS
#define	CONF_HFS_SUPPORT
#define	CONF_EXT2_SUPPORT
#define	CONF_EXT3_SUPPORT
#define	CONF_XFS_SUPPORT
#define	CONF_USB_MNT_ROOT	"/tmp/media/usb"
#define	CONF_MNT_POINT_FOR_SATA	"Local"
#define	CONF_EXPORT_STORAGE_MNT_POINT	"/tmp/media/export"
#define	CONF_USB_MNT_POINT_FOR_PORT1	"USB1"
#define	CONF_USB_MNT_POINT_FOR_PORT2	"USB2"
#define	CONF_USB_MNT_POINT_FOR_PORT	"USB"
#define	CONF_DBG_INFO_ON_USB
#define	CONF_REMOVABLE_DEVICE_MANAGER_VIRTUAL_FOLDER_FOR_LOCAL_BROWSE
#define	CONF_REMOVABLE_DEVICE_MANAGER_VF_LINKLIST
#define	CONF_REMOVABLE_DEVICE_MANAGER_VF_SUPPORT_INOTIFY
#define	CONF_REMOVABLE_DEVICE_MANAGER_VF_INOTIFY_REFRESH_DELAY	30
#define	CONF_ONE_DEVICE_FOR_EACH_USB_PORT
#define	CONF_CAS
#define	CONF_CASII_PARENTAL_CONTROL_DEFAULT_PASSWD	""
#define	CONF_TVDOCK_DB_DIR	"/.wd_tv/"
#define	CONF_TVDOCK_DB_NAME	"wdtv.cas"
#define	CONF_TVDOCK_UNION_DB_NAME	"uniondb.cas"
#define	CONF_TVDOCK_DB_MD5	".md5"
#define	CONF_CAS_FOLDER_CRC
#define	CONF_CAS_TIMER_INTERVAL	10
#define	CONF_REMOVABLE_DEVICE_BROWSE
#define	CONF_PTP_SUPPORT
#define	CONF_PTP_EXPORT_ONLY_IMAGE
#define	CONF_GPHOTO2_IDLIST	"/etc/idlist"
#define	CONF_POPEN_FIRMWARE_CHECKSUM
#define	CONF_SPU_API
#define	CONF_FONT_FILE_PATH_STORE	"/tmp/font_file_path"
#define	CONF_SUBTITLE_POSITION_ADJUSTMENT
#define	CONF_SUBTITLE_POSITION_ADJUSTMENT_DELTA	5
#define	CONF_SUPPORT_MICRODVD_SUBTITLE
#define	CONF_ONLINE_PLAYER_CACHE_SIZE	63963136
#define	CONF_AVI_SUPPORT_MULTIAUDIO_STREAM
#define	CONF_DMA_MLP_BOUNDED_WITH_RND
#define	CONF_PROCPIPE_PLAYER
#define	CONF_HW_BUFFERING
#define	CONF_ISO_FOLDER_SUPPORTED
#define	CONF_DTS_6CH_DIGITAL_COMPRESSED
#define	CONF_DTS_HRA_2CH_DIGITAL_COMPRESSED
#define	CONF_DTS_HRA_6CH_DIGITAL_COMPRESSED
#define	CONF_DTS_MA_2CH_DIGITAL_COMPRESSED
#define	CONF_DTS_MA_6CH_DIGITAL_COMPRESSED
#define	CONF_DOLBY_LL_2CH_ANALOG_COMPRESSED
#define	CONF_DOLBY_LL_2CH_DIGITAL_COMPRESSED
#define	CONF_DOLBY_LL_6CH_ANALOG_COMPRESSED
#define	CONF_DOLBY_LL_6CH_DIGITAL_COMPRESSED
#define	CONF_DOLBY_PLUS_2CH_DIGITAL_COMPRESSED
#define	CONF_DOLBY_PLUS_6CH_DIGITAL_COMPRESSED
#define	CONF_AC3_6CH_DIGITAL_COMPRESSED
#define	CONF_AAC_6CH_DIGITAL_COMPRESSED
#define	CONF_WMAPRO_6CH_DIGITAL_COMPRESSED
#define	CONF_PCM_FILE_SUPPORTED
#define	CONF_MUSIC_DIFFERENT_SPEED
#define	CONF_MUSIC_OGG
#define	CONF_MUSIC_FLAC
#define	CONF_FORMAT_MATROSKA
#define	CONF_SMOOTH_FASTFORWARD
#define	CONF_DMA_HW_AES
#define	CONF_PIPE_SG_PSF_PLAYER
#define	CONF_PIPE_AVI_PLAYER
#define	CONF_SPLIT_MEDIALOGIC
#define	CONF_PLAYER_NOTUSE_DEVICE_MEM
#define	CONF_HD_GFX_PHOTO_PLAYER
#define	CONF_BUFFER_WIDTH_FOR_HD_GFX_PHOTO_PLAYER	1920
#define	CONF_BUFFER_HEIGHT_FOR_HD_GFX_PHOTO_PLAYER	1080
#define	CONF_SCREEN_WIDTH_FOR_HD_GFX_PHOTO_PLAYER	1920
#define	CONF_SCREEN_HEIGHT_FOR_HD_GFX_PHOTO_PLAYER	1080
#define	CONF_SCREEN_NORNAL_WIDTH_FOR_HD_GFX_PHOTO_PLAYER	1440
#define	CONF_SCREEN_NORNAL_HEIGHT_FOR_HD_GFX_PHOTO_PLAYER	1080
#define	CONF_HW_PHOTO_DECODER
#define	CONF_MULTI_PLAYER_CACHE
#define	CONF_MULTI_PLAYER_CACHE_FOR_AV_PLAYER
#define	CONF_MULTI_PLAYER_CACHE_FOR_PIC_PLAYER
#define	CONF_MULTI_PLAYER_CACHE_SIZE	77
#define	CONF_QUICKTIME_PLAYER
#define	CONF_3GP_FILE_SUPPORT
#define	CONF_OGG_PLAYER
#define	CONF_SUBTITLE_DELAY
#define	CONF_VIDEO_PENDING_RELOAD_MICROCODE
#define	CONF_DIVX_SUBTITLE_SUPPORT
#define	CONF_FLV_PLAYER
#define	CONF_M4V_SUPPORT_TRICKMODE
#define	CONF_PGS_SUBTITLE_SUPPORT
#define	CONF_YOUTUBE_MOV_CACHE_PLAYER
#define	CONF_SW_DEFAULT_BPS_FOR_YOUTUBE	32768
#define	CONF_SW_MIN_BUFFERING_TIME_FOR_YOUTUBE	1
#define	CONF_SW_MAX_BUFFERING_TIME_FOR_YOUTUBE	15
#define	CONF_SW_FIRST_MAX_BUFFERING_TIME_FOR_YOUTUBE	6
#define	CONF_FAKE_BD_PLAYBACK
#define	CONF_DO_NOT_DOWNSAMPLE_FOR_ABOVE_48K_AUDIO
#define	CONF_OSDKEY_MAPPING
#define	CONF_KEYBOARD_IR_INJECTION
#define	CONF_WIZARD_IGNORE_QUEST_SERVER
#define	CONF_VOLUME_RNAGE_WORKAROUND
#define	CONF_DEFAULT_VOLUME	50
#define	CONF_VOLUME_SHOW_TIME	4
#define	CONF_UNIFORM_BROWSE
#define	CONF_SAVEMETHOD_CRC
#define	CONF_MAX_FILE_PATH_LENGTH	4353
#define	CONF_HTTP_HEADER_KEEP_ORIGINAL_HOSTNAME
#define	CONF_ACCOUNT_MGR
#define	CONF_ACCOUNT_FACTORY_SETTINGS	"account_list.xml"
#define	CONF_ACCOUNT_MSG_ONLING_YOUTUBE_SEARCH_MAX_ITEMS	50
#define	CONF_ACCOUNT_MGR_LOCAL_SAMBA_MAX_ITEMS	10
#define	CONF_ACCOUNT_MGR_LOCAL_NFS_MAX_ITEMS	10
#define	CONF_DMA_GPIO_API
#define	CONF_GPIO_LED_BLINKING
#define	CONF_LED_GPIO_PIN	2
#define	CONF_DEBUG_SECRET_TELNETD
#define	CONF_NO_SIGPIPE
#define	CONF_SHOW_INFO_BAR_WHILE_SWITCHING_REPEAT_MODE
#define	CONF_OSD_INFO_INDEPENDENCE
#define	CONF_NOW_PLAYING_INFO_SHOWN_ALL_THE_TIME
#define	CONF_BUG_2134_FIXED
#define	CONF_BUG_1332_FIXED
#define	CONF_BUG_798_FIXED
#define	CONF_BUG_1189_FIXED
#define	CONF_BUG_1767_FIXED
#define	CONF_BUG_1943_FIXED
#define	CONF_BUG_2972_FIXED
#define	CONF_ENABLE_BACK_BUTTON_ON_VIDEO_RESUME_PAGE
#define	CONF_SMALL_FOLDER_ICON_FOR_FOLDER_THUMB
#define	CONF_SUBTITLE_TURN_ON_OR_OFF_BY_DEFAULT
#define	CONF_SUBTITLE_OUTLINE_SHAPE
#define	CONF_PLAYLIST_SORT_BY_FILE
#define	CONF_AUDIO_TRACK_DISPLAY
#define	CONF_AUDIO_HIERARCHY_BROWSE
#define	CONF_AUTOPLAY
#define	CONF_SORT_BY_TRACK_NUMBER_WITH_ALBUM
#define	CONF_VIDEO_PLAYLIST
#define	CONF_FF_FB_LOOP_WITHOUT_NORMAL
#define	CONF_SEND_MUTE_SOUND_AT_BEGINNING
#define	CONF_HDMI_SIMPLAY_recover_from_HDMI_apply_fail
#define	CONF_NO_FF_FB_AT_PLAYER_PAUSE
#define	CONF_BUG_2849_FIX_CRASH_WHEN_CHANGE_OUTPUT_FROM_HDMI_TO_COMPOSITE_NTSC
#define	CONF_SORT_WITH_CASE_INSENSITIVE
#define	CONF_DLNA_CHOOSE_TRANSCODED_URI_FOR_WTV
#define	CONF_RALLY
#define	CONF_LLTD
#define	CONF_SUPPORT_RENDERER_USING_STATE
#define	CONF_SUPPORT_RENDERER_SELECT_PROFILE
#define	CONF_SETTING_ORIGINAL_CONFIG_FILE_DIR	"/conf_src"
#define	CONF_SETTING_FACTORY_SETTINGS	"config_factory_default"
#define	CONF_SETTING_CONFIG_FILE_DIR	"/tmp/conf/"
#define	CONF_SETTING_CONFIG_FILE_NAME	"config"
#define	CONF_RELATIVE_PATH_FOR_RESOURCES	""
#define	CONF_ROOTFS_SKELETON_GENERIC
#define	CONF_INSTALL_GLIBC
#define	CONF_GLIBC_2_8
#define	CONF_GLIBC_VERSION	"2.8_by_mips_4_3_2"
#define	CONF_BUSYBOX
#define	CONF_BUSYBOX_1_10_0
#define	CONF_BUSYBOX_1_10_0_CONFIG_FOR_NETWORKING
#define	CONF_BUSYBOX_VERSION	"1.10.0"
#define	CONF_ROOTFS_PRIMARY_SYSTEM_SKELETON_GENERIC
#define	CONF_BUSYBOX_PRIMARY_SYSTEM
#define	CONF_BUSYBOX_PRIMARY_SYSTEM_1_10_0
#define	CONF_BUSYBOX_PRIMARY_SYSTEM_1_10_0_CONFIG_GENERIC_WITH_MODULES
#define	CONF_BUSYBOX_PRIMARY_SYSTEM_VERSION	"1.10.0"
#define	CONF_FIRMWARE_UPGRADE_AFTER_REBOOT
#define	CONF_SYSCONFIG_PATH	"sysconfig"
#define	CONF_FIRMWARE_WDTV_SMP8654_WISTRON
#define	CONF_FIRMWARE_VALIDATE_FILENAME
#define	CONF_FIRMWARE_BLOCKING_ROLLBACK_VERSION	""
#define	CONF_FIRMWARE_VALIDATE_WITH_HIDE_INVALID
#define	CONF_FIRMWARE_VALIDATE_WITH_HIDE_INVALID_FILENAME
#define	CONF_FIRMWARE_VALIDATE_WITH_BLOCK_INVALID
#define	CONF_FIRMWARE_VALIDATE_WITH_BLOCK_INVALID_VERSION
#define	CONF_FIRMWARE_SCRIPT	"firmware_script_wdtv_smp8654_wistron.mk"
#define	CONF_FIRMWARE_FULL_UPGRADE_SMP8654
#define	CONF_FIRMWARE_VER_FILE	"wdtvlive.ver"
#define	CONF_FIRMWARE_BIN_FILE	"wdtvlive.bin"
#define	CONF_FIRMWARE_FULL_FILE	"wdtvlive.fff"
#define	CONF_NAND_FLASH_SIZE	268435456
#define	CONF_NAND_IMAGE_NO_YAMON
#define	CONF_BOOTLOADER_MTD_PARTITION	"/dev/sigmblocka"
#define	CONF_BOOTLOADER_MTD_SIZE	131072
#define	CONF_BOOTLOADER_UPGRADE
#define	CONF_MTD_BEFORE_YAMON_SIZE	524288
#define	CONF_MTD_YAMON_SIZE	262144
#define	CONF_DUAL_KERNEL
#define	CONF_KERNEL_MTD_PARTITION	"/dev/sigmblockd"
#define	CONF_KERNEL_MTD_MIRROR_PARTITION	"/dev/sigmblocke"
#define	CONF_MTD_IMAT_PARTITION	"/dev/sigmblockf"
#define	CONF_MTD_IMAT_SIZE	16777216
#define	CONF_MTD_IMAT_UPGRADE
#define	CONF_MTD_XMAT_PARTITION	"/dev/sigmblockg"
#define	CONF_MTD_XMAT_SIZE	8388608
#define	CONF_MTD_XMAT_UPGRADE
#define	CONF_FIRMWARE_MTD_PARTITION	"/dev/sigmblockh"
#define	CONF_MIRROR_FOR_SETTINGS
#define	CONF_CONFIG_MTD_PARTITION	"/dev/sigmblockj"
#define	CONF_CONFIG_MIRROR_MTD_PARTITION	"/dev/sigmblockk"
#define	CONF_PRIMARY_SYSTEM_SIZE	3145728
#define	CONF_APP_ROMFS_SIZE	94371840
#define	CONF_STORAGE_PARTITION_SIZE	94371840
#define	CONF_SETTINGS_PARTITION_SIZE	131072
#define	CONF_FLASH_BLOCK_SIZE	1048576
#define	CONF_KERNEL_PAGE_SIZE	16384
#define	CONF_SECURITY_USE_CPU_BINDING_PASSWORD	""
#define	CONF_BUILD_SIGMA_SDK
#define	CONF_LINUX_KERNEL_VERSION_2_6_22
#define	CONF_LINUX_KERNEL_VERSION_2_6_22_19_CONFIG_WDTV_HUT_SMP8654_WISTRON
#define	CONF_BUILD_ZBOOT
#define	CONF_SQUEEZE_XENV_ZBOOT_YAMON
#define	CONF_FONTS
#define	CONF_FREETYPE
#define	CONF_FREETYPE_2_3_7
#define	CONF_FREETYPE_STATIC_LIB
#define	CONF_FREETYPE_VERSION	"2.3.7"
#define	CONF_FONT_ARPHIC
#define	CONF_FONT_ARPHIC_MOBILE_FONT
#define	CONF_FONTS_VERSION	"arphic_mbf"
#define	CONF_FONTS_LIB_TYPE_ALL
#define	CONF_FONT_SPU_PLAYER_USE_MBF
#define	CONF_FLAC
#define	CONF_FLAC_1_2_1
#define	CONF_FLAC_VERSION	"1.2.1"
#define	CONF_LIBICONV
#define	CONF_LIBICONV_1_12
#define	CONF_LIBICONV_VERSION	"1.12"
#define	CONF_LIBJPEG
#define	CONF_LIBJPEG_V6B
#define	CONF_LIBJPEG_VERSION	"v6b"
#define	CONF_LIBPNG
#define	CONF_LIBPNG_1_2_14
#define	CONF_LIBPNG_VERSION	"1.2.14"
#define	CONF_LIBUNGIF
#define	CONF_LIBUNGIF_4_1_3
#define	CONF_LIBUNGIF_VERSION	"4.1.3"
#define	CONF_LIBCX
#define	CONF_LIBCX_1_1_1
#define	CONF_LIBCX_VERSION	"1.1.1"
#define	CONF_DIRECTFB
#define	CONF_TINYXML
#define	CONF_TINYXML_2_5_3
#define	CONF_TINYXML_VERSION	"2_5_3"
#define	CONF_MXML
#define	CONF_MXML_2_6
#define	CONF_MXML_VERSION	"2.6"
#define	CONF_TIFF
#define	CONF_TIFF_3_7_1
#define	CONF_TIFF_VERSION	"3.7.1"
#define	CONF_TREMOR
#define	CONF_TREMOR_1_0_SVN
#define	CONF_TREMOR_VERSION	"1.0-svn"
#define	CONF_DHCPCD
#define	CONF_DHCPCD_1_3_22_PL1
#define	CONF_DHCPCD_VERSION	"1.3.22-pl1"
#define	CONF_CURL
#define	CONF_CURL_7_19_3
#define	CONF_CURL_VERSION	"7.19.3"
#define	CONF_OPENSSL
#define	CONF_OPENSSL_0_9_8_k
#define	CONF_OPENSSL_VERSION	"0.9.8k"
#define	CONF_NTFS_3G_2009_4_4
#define	CONF_NTFS_3G_VERSION	"2009.4.4"
#define	CONF_FLICKR
#define	CONF_XML2
#define	CONF_HOWL_1_0_0
#define	CONF_HOWL_VERSION	"1.0.0"
#define	CONF_SDPARM
#define	CONF_LIBMCRYPT
#define	CONF_NTP
#define	CONF_UUID
#define	CONF_UUID_VERSION	"1.41.10"
#define	CONF_XFS
#define	CONF_PCRE
#define	CONF_PCRE_VERSION	"8.02"
#define	CONF_LIBMMS
#define	CONF_LIBMMS_0_5
#define	CONF_LIBMMS_VERSION	"0.5-radiotime"
#define	CONF_SQLITE
