#!/bin/sh

/bin/mount -t proc none /proc
mount -t sysfs sysfs /sys
echo /sbin/mdev > /proc/sys/kernel/hotplug
mount -t tmpfs mdev /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts
mdev -s
mount -t tmpfs none /tmp
/bin/hostname -F /etc/hostname

/sbin/ldconfig -C /tmp/ld.so.cache
/sbin/config_tool -l -m 10 &
