include $(RT28xx_DIR)/os/linux/config.mk

MOD_NAME = rt$(CHIPSET)sta
DAT_PATH = $(TOP)/build/root/etc/
SRC_DAT_FILE_NAME = RT2870STA.dat
DST_DAT_FILE_NAME = RT$(CHIPSET)STA.dat


obj-m := $(MOD_NAME).o


#ifdef CONFIG_STA_SUPPORT
rt$(CHIPSET)sta-objs := \
	../../common/crypt_md5.o\
	../../common/crypt_sha2.o\
	../../common/crypt_hmac.o\
	../../common/mlme.o\
	../../common/cmm_wep.o\
	../../common/action.o\
	../../common/cmm_data.o\
	../../common/rtmp_init.o\
	../../common/cmm_tkip.o\
	../../common/cmm_aes.o\
	../../common/cmm_sync.o\
	../../common/eeprom.o\
	../../common/cmm_sanity.o\
	../../common/cmm_info.o\
	../../common/cmm_cfg.o\
	../../common/cmm_wpa.o\
	../../common/dfs.o\
	../../common/spectrum.o\
	../../common/rtmp_timer.o\
	../../common/rt_channel.o\
	../../common/cmm_profile.o\
	../../common/cmm_asic.o\
	../../sta/assoc.o\
	../../sta/auth.o\
	../../sta/auth_rsp.o\
	../../sta/sync.o\
	../../sta/sanity.o\
	../../sta/rtmp_data.o\
	../../sta/connect.o\
	../../sta/wpa.o\
	../../os/linux/rt_linux.o\
	../../os/linux/rt_profile.o\
	../../os/linux/rt_main_dev.o\
	../../os/linux/sta_ioctl.o

#ifdef DOT11_N_SUPPORT
ifeq ($(HAS_DOT11_N_SUPPORT),y)
rt$(CHIPSET)sta-objs += \
	../../common/ba_action.o
endif
#endif // DOT11_N_SUPPORT //


#ifdef WSC_INCLUDED
ifeq ($(HAS_WSC),y)
rt$(CHIPSET)sta-objs += \
	../../common/wsc.o\
	../../common/wsc_tlv.o\
	../../common/crypt_biginteger.o\
	../../common/crypt_dh.o\
	../../common/crypt_aes.o\
	../../common/dh_key.o\
	../../common/evp_enc.o
endif
#endif // WSC_INCLUDED //

ifeq ($(HAS_BLOCK_NET_IF),y)
rt$(CHIPSET)sta-objs += ../../common/netif_block.o
endif

ifeq ($(HAS_QOS_DLS_SUPPORT),y)
rt$(CHIPSET)sta-objs += ../../sta/dls.o
endif

#ifdef RT2860
ifeq ($(CHIPSET),2860)
rt$(CHIPSET)sta-objs += \
	../../os/linux/pci_main_dev.o\
	../../os/linux/rt_pci_rbus.o\
	../../common/cmm_mac_pci.o\
	../../common/cmm_data_pci.o\
	../../common/ee_prom.o\
	../../common/rtmp_mcu.o
endif
#endif // RT2860 //

#ifdef RT3090
ifeq ($(CHIPSET),3090)
rt$(CHIPSET)sta-objs += \
	../../os/linux/pci_main_dev.o\
	../../os/linux/rt_pci_rbus.o\
	../../common/cmm_mac_pci.o\
	../../common/cmm_data_pci.o\
	../../common/ee_prom.o\
	../../common/ee_efuse.o\
	../../common/rtmp_mcu.o\
	../../chips/rt30xx.o\
	../../common/rt_rf.o\
	../../chips/rt3090.o
endif
#endif // RT3090 //

#ifdef RT2870
ifeq ($(CHIPSET),2870)
rt$(CHIPSET)sta-objs += \
	../../os/linux/usb_main_dev.o\
	../../os/linux/rt_usb.o\
	../../common/cmm_mac_usb.o\
	../../common/rtusb_io.o\
	../../common/rtusb_bulk.o\
	../../common/rtusb_data.o\
	../../common/cmm_data_usb.o\
	../../common/ee_prom.o\
	../../common/rtmp_mcu.o
endif
#endif // RT2870 //

#ifdef RT3070
ifeq ($(CHIPSET),2070)
rt$(CHIPSET)sta-objs += \
	../../os/linux/usb_main_dev.o\
	../../os/linux/rt_usb.o\
	../../common/cmm_mac_usb.o\
	../../common/rtusb_io.o\
	../../common/rtusb_bulk.o\
	../../common/rtusb_data.o\
	../../common/cmm_data_usb.o\
	../../common/ee_prom.o\
	../../common/ee_efuse.o\
	../../common/rtmp_mcu.o\
	../../chips/rt30xx.o\
	../../common/rt_rf.o\
	../../chips/rt3070.o
endif

ifeq ($(CHIPSET),3070)
rt$(CHIPSET)sta-objs += \
	../../os/linux/usb_main_dev.o\
	../../os/linux/rt_usb.o\
	../../common/cmm_mac_usb.o\
	../../common/rtusb_io.o\
	../../common/rtusb_bulk.o\
	../../common/rtusb_data.o\
	../../common/cmm_data_usb.o\
	../../common/ee_prom.o\
	../../common/ee_efuse.o\
	../../common/rtmp_mcu.o\
	../../chips/rt30xx.o\
	../../common/rt_rf.o\
	../../chips/rt3070.o
endif
#endif // RT3070 //

#ifdef RT2880
ifeq ($(CHIPSET),2880)
rt$(CHIPSET)sta-objs += \
	../../os/linux/rbus_main_dev.o\
	../../os/linux/rt_pci_rbus.o\
	../../common/cmm_mac_pci.o\
	../../common/cmm_data_pci.o\
	../../common/ee_flash.o
endif
#endif // RT2880 //

#ifdef RT35xx
ifeq ($(CHIPSET),3572)
rt$(CHIPSET)sta-objs += \
	../../os/linux/usb_main_dev.o\
	../../os/linux/rt_usb.o\
	../../common/cmm_mac_usb.o\
	../../common/rtusb_io.o\
	../../common/rtusb_bulk.o\
	../../common/rtusb_data.o\
	../../common/cmm_data_usb.o\
	../../common/ee_prom.o\
	../../common/ee_efuse.o\
	../../common/rtmp_mcu.o\
	../../chips/rt30xx.o\
	../../common/rt_rf.o\
	../../chips/rt35xx.o
endif

ifeq ($(CHIPSET),3562)
rt$(CHIPSET)sta-objs += \
	../../os/linux/pci_main_dev.o\
	../../os/linux/rt_pci_rbus.o\
	../../common/cmm_mac_pci.o\
	../../common/cmm_data_pci.o\
	../../common/rtmp_mcu.o\
	../../common/ee_prom.o\
	../../common/ee_efuse.o\
	../../common/rt_rf.o\
	../../chips/rt30xx.o\
	../../chips/rt35xx.o
endif
#endif // RT35xx //

ifeq ($(HAS_ATE),y)
rt$(CHIPSET)sta-objs += ../../os/linux/rt_ate.o
endif





#endif // CONFIG_STA_SUPPORT //


clean:
	rm -f ../../common/*.o
	rm -f ../../common/.*.{cmd,flags,d}
	rm -f ../../os/linux/*.{o,ko,mod.{o,c}}
	rm -f ../../os/linux/.*.{cmd,flags,d}
	rm -fr ../../os/linux/.tmp_versions
	rm -f ../../chips/*.o
	rm -f ../../chips/.*.{cmd,flags,d}
ifeq ($(RT28xx_MODE),AP)
	rm -f ../../ap/*.o
	rm -f ../../ap/.*.{cmd,flags,d}
else
ifeq ($(RT28xx_MODE),STA)
	rm -f ../../sta/*.o
	rm -f ../../sta/.*.{cmd,flags,d}
else
ifeq ($(RT28xx_MODE),APSTA)
	rm -f ../../ap/*.o
	rm -f ../../ap/.*.{cmd,flags,d}
	rm -f ../../sta/*.o
	rm -f ../../sta/.*.{cmd,flags,d}
endif
endif
endif

install:
	mkdir -p $(DAT_PATH)
	cp $(RT28xx_DIR)/$(SRC_DAT_FILE_NAME) $(DAT_PATH)/$(DST_DAT_FILE_NAME)
	install -d $(LINUX_SRC_MODULE)
	install -m 644 -c $(addsuffix .ko,$(MOD_NAME)) $(LINUX_SRC_MODULE)

uninstall:
#	rm -rf $(DAT_PATH)
	rm -rf $(addprefix $(LINUX_SRC_MODULE),$(addsuffix .ko,$(MOD_NAME)))
	/sbin/depmod -a ${shell uname -r}
